[package]
name = "nowoshire/namedsignal"
description = "A Luau signal that allows the naming and definition of variadic parameters, and fully complies with modern standards, such as Synchronous FRP (Functional Reactive Programming) with Atomic Propagation."
version = "1.2.0"
license = "MIT"
authors = ["Nowoshire"]

registry = "https://github.com/UpliftGames/wally-index"
homepage = "https://nowoshire.github.io/NamedSignal/"
repository = "https://github.com/Nowoshire/NamedSignal"

realm = "shared"
include = ["src/init.luau"]

[dependencies]
