[package]
name = "nowoshire/namedsignal"
description = "A Luau signal implementation that lets you name and define variadic parameters â€” conveniently."
version = "1.0.0"
license = "MIT"
authors = ["Nowoshire"]

registry = "https://github.com/UpliftGames/wally-index"
homepage = "https://nowoshire.github.io/NamedSignal/"
repository = "https://github.com/Nowoshire/NamedSignal"

realm = "shared"
include = ["src/init.luau"]

[dependencies]
